### ISSUE TITLE
How to debug plugin

### ISSUE THREAD

**Issue by asebak** [MoreUnit/org.moreunit.intellij.plugin#1]
I built your project. But when you run your launch configuration Intellij doesn't recognize it (doesnt get installed in the plugins list). Do you need to additional steps?

**Comment by asebak** [comment]
seems like it works when you manually install the jar in intellij in the plugins section? Is there not automatic deployment mechanism you have in place to install in intellij? not sure if you have this issue too, where you would make  a small code change and uninstall and reinstall the plugin

**Comment by ndemengel** [comment]
Hi aseback,

To be honest, I found IntelliJ plugin run configuration to be a mess, and I had a lot of issues before I could make it work.
That said, I just made a fresh checkout of the project, and imported it in a - hopefully - virgin IntelliJ workspace. I then followed [the "getting started" instructions](https://github.com/MoreUnit/org.moreunit.intellij.plugin#getting-started) in the given order, and it worked.

Some checks I can think of:
- After having created the IntelliJ SDK, ensure the project SDK is properly set to that SDK (in the "Project Structure" window). The first time you import the project, the SDK doesn't exist yet, so IntelliJ may remove it from the project structure. Maybe I should switch those two steps in the instructions ("creating the SDK" and "importing the project").
- Ensure you didn't run into [this problem](https://github.com/MoreUnit/org.moreunit.intellij.plugin#common-problems)
- Have a look at the SDK sandbox home directory (see the SDK configuration): after having run the "Launch Plugin" configuration once, it should contain the plugin classes in `plugins/org.moreunit.intellij.plugin/`

**Comment by asebak** [comment]
but i am curious so you dont need to install and uninstall the plugin? You just press the debug button for the plugin and it always has the latest code?

**Comment by ndemengel** [comment]
Yep, that's it!

**Comment by asebak** [comment]
alright I will check out your steps to make sure I followed it correctly.  The thing is I believe you are using MAC? I don't have a jdk.table.xml file that gets generated I think its called something else.

**Comment by ndemengel** [comment]
On Windows, it should be under `c:\Documents and Settings\${userName}\.IdeaIC14\config\options\jdk.table.xml`
