### ISSUE TITLE
Exception while starting IntelliJ

### ISSUE THREAD

**Issue by gianasista** [MoreUnit/org.moreunit.intellij.plugin#2]
Today I got the following exception when I started IntelliJ:

`09:53:27 IllegalArgumentException: Argument for @NotNull parameter 'focusedFile' of org/moreunit/intellij/plugin/navigation/FileEditorHistory.fileFocused must not be null`

Never had this problem before

**Comment by ndemengel** [comment]
Looks like I misunderstood the lifecycle of editor tabs... Let me guess: it occurred when closing the last tab?

I will fix that during lunch time.

**Comment by ndemengel** [comment]
(BTW, sorry for my question... You wrote it clearly enough: "while starting IntelliJ" :-\)
