### ISSUE TITLE
Support for custom test file suffix

### ISSUE THREAD

**Issue by aleitamar** [MoreUnit/org.moreunit.intellij.plugin#8]
Hi,

I was wondering if you are willing to support external configuration of test file patterns (like the MoreUnit plugin for Eclipse enables)

Our team uses the convention of using a suffix of 'Tests' for test files, so we can't use the plugin if keep this convention.

As an alternative, i don't mind adding the 'Tests' suffix specifically if this is fine with you...

Thanks

**Comment by ndemengel** [comment]
Hi @aleitamar,

To be honest, I find a zero-conf approach to be preferable as long as it's possible without drawbacks, and I know of enough people making use of the "Tests" suffix to consider it as another valid default. Therefore I guess that adding it to the code is fine ;-)

Regards
